name: Python Tests
run-name: Run Tests by ${{ github.actor }}
on: [push, pull_request, workflow_dispatch]
jobs:
  tests:
    env:
      FORCE_COLOR: 1
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: true
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install prereq
        run: pip install tox coveralls
      - name: Run python tests
        run: tox -e ${{ matrix.python }}
      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
          COVERALLS_PARALLEL: true
        run: coveralls
  coveralls:
    name: Indicate completion to coveralls.io
    needs: tests
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - name: Finished
        run: |
          pip3 install --upgrade coveralls
          coveralls --service=github --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  docs:
    strategy:
      matrix:
        toxenv: ["docs", "readme"]
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install -y graphviz
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install prereq
        run: pip install tox
      - name: Run python tests
        run: tox -e ${{ matrix.toxenv }}
